########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]
logging = "warn"

# Reposiory Name. It is used for solution name and final package name
name = "ComfyUI-RTX_Remix"


########################################################################################################################
# Package publishing to packman
########################################################################################################################

[repo_publish]
enabled = true

packages = ["*"]

########################################################################################################################
# Packaging
########################################################################################################################

[repo_package]

[repo_package.packages.main_package]

default = true
omniverse_flow_version_scheme = true
archive_name = "${conf:repo.name}"
archive_format = "zip"

windows_max_path_length = 240
files = [
    ["**"],
]
files_exclude = [
    ["tools/**"],
    ["_*/**"],
    ["repo*"],
    [".*"],
]


# python is formatted with black+isort:
[repo_format.python]
files.include = ["nodes/*.py"]
files.exclude = []
python_version = "py311"
job_count = 1


########################################################################################################################
# Python lint tool
########################################################################################################################

[repo_lint.flake8]
files.include = ["nodes/*.py"]
files.exclude = []
