[repo_class_docs]
# Tool name
command = "class_docs"
# [python module name or path]:[function name]
entry_point = "${root}/tools/repoman/class_docs.py:setup_repo_tool"
# Python install to use
python_install = "${root}/../../../python_embeded/python.exe"
# Root module to import
module_name = "nodes"
module = "${root}/nodes/__init__.py"
# README to modify
file_path = "${root}/README.md"
# Header of section where change is required
section_header = "## Nodes"